/*! ContactUsView */
define(["jquery","underscore","backbone","text!tpl/prelogin/contact_us.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#index_li").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);return this}});return d});
/*! FaqsView */
define(["jquery","underscore","backbone","text!tpl/prelogin/faqs.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#sideNav_faqs").siblings().removeAttr("class");c("#learnmore_li").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);c("#sideNav_faqs").addClass("selected");c("#learnmore_li").addClass("selected");return this}});return d});
/*! FooterView */
define(["jquery","underscore","backbone","text!tpl/prelogin/footer.html"],function(c,a,e,b){var d=e.View.extend({el:"#footer_containerarea",template:a.template(b),render:function(){var f=this;this.$el.html(this.template);return this},events:{"click #termstext, #privacytext, #contacttext":"hideLogin"},hideLogin:function(f){c("#LoginForm").addClass("hidden-md hidden-sm hidden-lg");c("#logincontainer").each(function(g){c(this).children().each(function(){var h=c(this).attr("id");c("#"+h).removeClass("preloginLinksSelected")})})}});return d});
/*! GetStartedView */
define(["jquery","underscore","backbone","text!tpl/prelogin/get_started.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#index_li").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);c("#get_started_li").addClass("selected");return this}});return d});
/*! HeaderView */
define(["jquery","underscore","backbone","text!tpl/prelogin/header.html","jquery-ui"],function(c,a,e,b){var d=e.View.extend({el:"#header_container",template:a.template(b),render:function(){var f=this;this.$el.html(this.template);this.$el.find("#index_tab, #index_modal_tab").addClass("selected");this.$el.find("#menu-tab-sm-btn>.selected").html("Home");return this},events:{"submit #loginform":"btnSignup","click #index_tab, #learnmore_tab, #faqs_tab, #download_tab, #claim_tab, #index_modal_tab, #faqs_modal_tab, #download_modal_tab, #learnmore_modal_tab, #claim_modal_tab":"togglePreloginMenu"},btnSignup:function(f){f.preventDefault();this.$el.find("#btnSignup").val("Submitting...");return validateLogin(document.login)},togglePreloginMenu:function(f){hashTag=c(f.currentTarget).attr("tag");ref=c(f.currentTarget).attr("ref");t=c(f.currentTarget).attr("id");(ref!="")?location.href=location.pathname+"#"+hashTag:window.open(hashTag,"_fileclaim");this.$el.find("#menu-tab-sm-btn>.selected").html(this.$el.find("#"+ref+"_modal_tab").html());this.$el.find("#"+ref+"_tab, #"+ref+"_modal_tab").addClass("selected").siblings().removeClass("selected")}});return d});
/*! IndexView */
define(["jquery","underscore","backbone","text!tpl/prelogin/index.html","jquery-ui"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#index_li").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);c("#index_li").addClass("selected");return this}});return d});
/*! LearnMoreView */
define(["jquery","underscore","backbone","text!tpl/prelogin/learn_more.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#sideNav_about_menu").siblings().removeAttr("class");c("#learnmore_li").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);c("#sideNav_about_menu").addClass("selected");c("#learnmore_li").addClass("selected");return this}});return d});
/*! LoginInvalidView */
define(["jquery","underscore","backbone","text!tpl/prelogin/login_invalid.html","jquery-ui"],function(c,a,e,b){var d=e.View.extend({el:"#header_container",template:a.template(b),initialize:function(){c("#index_li").siblings().removeAttr("class");this.$el.find("#index_tab, #index_modal_tab").addClass("selected");this.$el.find("#menu-tab-sm-btn>.selected").html("Home")},render:function(){var f=this;this.$el.html(this.template);c("#index_li").addClass("selected");return this},events:{"submit #loginform":"btnSignup","click #home_prelogin, #learnmore_prelogin, #phones_prelogin, #faqs_prelogin, #download_prelogin, #claim_prelogin":"togglePreloginMenu"},togglePreloginSMMenu:function(f){hashTag=c(f.currentTarget).attr("tag");ref=c(f.currentTarget).attr("ref");t=c(f.currentTarget).attr("id");(ref!="")?location.href=location.pathname+"#"+hashTag:window.open(hashTag,"_fileclaim");this.$el.find("#menu-tab-sm-btn>.selected").html(this.$el.find("#"+ref+"_modal_tab").html());this.$el.find("#"+ref+"_tab, #"+ref+"_modal_tab").addClass("selected").siblings().removeClass("selected")}});return d});
/*! PasswordResetView */
define(["jquery","underscore","backbone","text!tpl/prelogin/password_reset.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){var f=this;c("#sideNav_privacy_policy").siblings().removeAttr("class");this.$el.off().on("submit","form[name=updateAccountPassword]",function(g){g.preventDefault();getSecretPair(a.bind(f.createNewPassword,f))})},render:function(){var g=this;var f=AMA.config.apiHostUrl+"/accounts/passwordReset/change?"+c.param({devId:AMA.config.devId});this.$el.html(this.template);c("form[name=updateAccountPassword]").attr("action",f);return this},events:{"click #resetPasswordBtn":"btn_submit"},btn_submit:function(h){var i=c.trim(this.$el.find("[name=newpin1]").val()),f=c.trim(this.$el.find("[name=confirmpin1]").val()),g=/^\s*[a-zA-Z0-9,\s]+\s*$/;if(i.length<6||i.length>15){AMA.Util.switchLabel(".validation_text",".password_length",this.$el.find(".validation_pinInfo"));return false}if(i.length>0&&!g.test(i)){AMA.Util.switchLabel(".validation_text",".special_chars",this.$el.find(".validation_pinInfo"));return false}if(i!==f){AMA.Util.switchLabel(".validation_text",".not_match",this.$el.find(".validation_pinInfo"));return false}this.$el.find("form").submit()},createNewPassword:function(h){if(typeof h!=="object"){h=JSON.parse(this.responseText)}if(!h){return}var o=getCookie("u_token");var k={secretHandle:h.handle,uniqueToken:o};var m=CryptoJS.enc.Hex.parse(h.secretKey);var g=CryptoJS.enc.Hex.parse(h.initVector);var l=this.$el.find("[name=newpin1]").val();var j=this.$el.find("[name=confirmpin1]").val();var n=CryptoJS.AES.encrypt(l,m,{iv:g});var p=CryptoJS.AES.encrypt(j,m,{iv:g});var f=this.$el.find("form[name=updateAccountPassword]").attr("action");k.newPassword=n.toString();k.confirmPassword=p.toString();AMA.debug("Sending AJAX request: "+f);var i=createCORSRequest.call(this,"POST",f);if(i){i.setRequestHeader("Content-type","application/json");i.onerror=function(r,q,s){AMA.ActionManager._onAjaxError(r,q,s);window.location="#password_reset_failed"};i.onreadystatechange=function(){if(i.readyState===4&&i.status===200){window.location="#password_reset_successful"}};i.send(JSON.stringify(k))}}});return d});
/*! PasswordRetrieveSecureView */
define(["jquery","underscore","backbone","text!tpl/prelogin/password_retrieve_secure.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){var f=this;c("#sideNav_privacy_policy").siblings().removeAttr("class");this.$el.off().on("submit","form[name=sendpasswd]",function(g){g.preventDefault();getSecretPair(a.bind(f.submitAnswer,f))})},render:function(){var g=this;var f=AMA.config.apiHostUrl+"/accounts/passwordReset/validate?"+c.param({devId:AMA.config.devId});this.$el.html(this.template);c("form[name=sendpasswd]").attr("action",f);this.$el.find("#securityquestion").text(this.options.securityQuestion);return this},events:{"click #submitSecurityAnswer":"btn_submit"},btn_submit:function(f){f.preventDefault();if(checkSecurityAnswer(document.sendpasswd)){this.$el.find("form").submit()}},submitAnswer:function(g){if(typeof g!=="object"){g=JSON.parse(this.responseText)}if(!g){return}var l={secretHandle:g.handle,uniqueToken:this.options.uniqueToken};var i=CryptoJS.enc.Hex.parse(g.secretKey);var f=CryptoJS.enc.Hex.parse(g.initVector);var k=this.$el.find("[name=securityanswer]").val();var m=CryptoJS.AES.encrypt(k,i,{iv:f});var h=this.$el.find("form[name=sendpasswd]").attr("action");l.securityAnswer=m.toString();setCookie("u_token",l.uniqueToken,1);AMA.debug("Sending AJAX request: "+h);var j=createCORSRequest.call(this,"POST",h);if(j){j.setRequestHeader("Content-type","application/json");j.onerror=function(o,n,p){AMA.debug("AJAX Request to "+h+" returns "+j.status);c("#wronganswer").show()};j.onreadystatechange=function(){if(j.readyState===4&&j.status===200){window.location="#password_reset"}};j.send(JSON.stringify(l))}}});return d});
/*! PasswordSentEmailView */
define(["jquery","underscore","backbone","text!tpl/prelogin/password_sent_email.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#sideNav_privacy_policy").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);return this}});return d});
/*! PhonesSupportedView */
define(["jquery","underscore","backbone","text!tpl/prelogin/phones_supported.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#sideNav_supported_phones").siblings().removeAttr("class");c("#learnmore_li").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);c("#sideNav_supported_phones").addClass("selected");c("#learnmore_li").addClass("selected");return this}});return d});
/*! PrivacyView */
define(["jquery","underscore","backbone","text!tpl/prelogin/privacy.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#sideNav_privacy_policy").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);c("#sideNav_privacy_policy").addClass("selected");return this},events:{"click #termstext":"hideLogin"},hideLogin:function(f){alert("hiding login");clink.indexOf("home")==-1?$el.find("#LoginForm").addClass("hidden-md hidden-sm hidden-lg"):$el.find("#LoginForm").removeClass("hidden-md hidden-sm hidden-lg")}});return d});
/*! RetrievePinView */
define(["jquery","underscore","backbone","text!tpl/prelogin/retrieve_pin.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#index_li").siblings().removeAttr("class");var f=0;$el=this.$el;this.$el.on("submit","form[name=retrievePin]",function(j){j.preventDefault();var g=c(this).attr("action");var i=JSON.stringify({email:c(this).find("[name=email]").val()});AMA.debug("Sending AJAX request: "+g);var h=createCORSRequest.call(this,"POST",g);if(h){h.setRequestHeader("Content-type","application/json");h.onerror=function(l,k,m){AMA.debug("AJAX Request to "+g+" returns "+h.status);AMA.Util.switchLabel(".validation_text",".email_empty",this.$el.find(".validation_accountinfo2"))};h.onreadystatechange=function(){if(h.readyState===4&&h.status===200){window.location="#password_sent_email"}else{if(h.readyState===4&&h.status===500){var k=JSON.parse(h.responseText);$el.find(".pin_error").html(k.error);AMA.Util.switchLabel(".validation_text",".email_empty",$el.find(".validation_accountinfo2"))}}};h.send(i)}else{alert("test")}})},render:function(){var g=this;var f=AMA.config.apiHostUrl+"/accounts/passwordReset/send?"+c.param({devId:AMA.config.devId});this.$el.html(this.template);c("form[name=retrievePin]").attr("action",f);return this},events:{"click #triggerPinChange":"btn_submit"},btn_submit:function(g){var f=/^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i,g=this.$el.find("[name=email]").val();if(!f.test(g)){AMA.Util.switchLabel(".validation_text",".email_empty",this.$el.find(".validation_accountinfo2"));return false}this.$el.find("form").submit()}});return d});
/*! TermsView */
define(["jquery","underscore","backbone","text!tpl/prelogin/terms.html"],function(c,a,e,b){var d=e.View.extend({el:"#body_container",template:a.template(b),initialize:function(){c("#sideNav_terms_and_conditions").siblings().removeAttr("class")},render:function(){var f=this;this.$el.html(this.template);c("#sideNav_terms_and_conditions").addClass("selected");return this},events:{"click #termstext, #termstext":"hideLogin"},hideLogin:function(f){alert("hiding login")}});return d});